# Generated by Django 5.0.4 on 2024-06-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_userpreference_detectives_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='detectives_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='fantasy_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='fighters_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='romantics_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='thrillers_count',
            field=models.IntegerField(default=0),
        ),
    ]
