# Generated by Django 5.0.4 on 2024-06-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_userpreference_detectives_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
