# Generated by Django 5.0.4 on 2024-06-18 09:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='search_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=''), default=list, size=None),
        ),
    ]
