# Generated by Django 5.0.4 on 2024-06-18 09:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_customuser_search_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='search_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=''), default=list, max_length=5, size=None),
        ),
    ]
