# Generated by Django 5.0.4 on 2024-06-22 12:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_customuser_views_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_books',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=None),
        ),
    ]
